# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cde35f04d93235049f1306fb8c277d06"
name = "Shop-Sizer"
application_url = "https://unix-though-proceeding-indicated.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-test-web-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://unix-though-proceeding-indicated.trycloudflare.com/auth/callback",
  "https://unix-though-proceeding-indicated.trycloudflare.com/auth/shopify/callback",
  "https://unix-though-proceeding-indicated.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
